import jsPDF from 'jspdf';
import 'jspdf-autotable';

const formatCurrency = (value) => {
  if (!value && value !== 0) return 'R 0';
  return 'R ' + Math.round(value).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ' ');
};

export const exportCashflowToPDF = (netSalary, carBudget, houseBudget, customExpenses, savings) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text('Cashflow Statement', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by Nickle', 105, 27, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), 105, 32, { align: 'center' });
  
  let yPos = 45;
  
  // INCOME Section
  doc.setFontSize(14);
  doc.setTextColor(34, 139, 34);
  doc.text('INCOME', 20, yPos);
  
  yPos += 5;
  doc.autoTable({
    startY: yPos,
    head: [['Category', 'Amount']],
    body: [
      ['Employment (Net)', formatCurrency(netSalary)]
    ],
    theme: 'grid',
    headStyles: { fillColor: [34, 139, 34] },
    margin: { left: 20, right: 20 },
  });
  
  yPos = doc.lastAutoTable.finalY + 2;
  doc.setFontSize(12);
  doc.setTextColor(34, 139, 34);
  doc.text(`Total Income: ${formatCurrency(netSalary)}`, 150, yPos, { align: 'right' });
  
  yPos += 10;
  
  // EXPENSES Section
  doc.setFontSize(14);
  doc.setTextColor(255, 140, 0);
  doc.text('EXPENSES', 20, yPos);
  
  yPos += 5;
  const expenseRows = [];
  
  // House breakdown
  if (houseBudget && houseBudget.breakdown) {
    expenseRows.push(['House', '']);
    expenseRows.push(['  Bond Repayment', formatCurrency(houseBudget.breakdown.bondRepayment)]);
    expenseRows.push(['  Rates & Taxes', formatCurrency(houseBudget.breakdown.rates)]);
    expenseRows.push(['  Home Insurance', formatCurrency(houseBudget.breakdown.insurance)]);
    expenseRows.push(['  Maintenance', formatCurrency(houseBudget.breakdown.maintenance)]);
  }
  
  // Car breakdown
  if (carBudget && carBudget.breakdown) {
    expenseRows.push(['Car', '']);
    expenseRows.push(['  Monthly Repayment', formatCurrency(carBudget.breakdown.repayment)]);
    expenseRows.push(['  Insurance', formatCurrency(carBudget.breakdown.insurance)]);
    expenseRows.push(['  Petrol', formatCurrency(carBudget.breakdown.petrol)]);
  }
  
  // Custom expenses
  customExpenses.forEach(expense => {
    if (expense.amount > 0) {
      expenseRows.push([expense.name, formatCurrency(expense.amount)]);
    }
  });
  
  doc.autoTable({
    startY: yPos,
    head: [['Category', 'Amount']],
    body: expenseRows,
    theme: 'grid',
    headStyles: { fillColor: [255, 140, 0] },
    margin: { left: 20, right: 20 },
  });
  
  const totalExpenses = 
    (houseBudget ? houseBudget.totalMonthlyCost : 0) +
    (carBudget ? carBudget.totalMonthlyCost : 0) +
    customExpenses.reduce((sum, exp) => sum + (exp.amount || 0), 0);
  
  yPos = doc.lastAutoTable.finalY + 2;
  doc.setFontSize(12);
  doc.setTextColor(255, 140, 0);
  doc.text(`Total Expenses: ${formatCurrency(totalExpenses)}`, 150, yPos, { align: 'right' });
  
  yPos += 10;
  
  // SAVINGS Section
  doc.setFontSize(14);
  doc.setTextColor(147, 51, 234);
  doc.text('SAVINGS', 20, yPos);
  
  yPos += 5;
  const savingsRows = savings
    .filter(sav => sav.amount > 0)
    .map(sav => [sav.name, formatCurrency(sav.amount)]);
  
  if (savingsRows.length > 0) {
    doc.autoTable({
      startY: yPos,
      head: [['Category', 'Amount']],
      body: savingsRows,
      theme: 'grid',
      headStyles: { fillColor: [147, 51, 234] },
      margin: { left: 20, right: 20 },
    });
    
    yPos = doc.lastAutoTable.finalY + 2;
  }
  
  const totalSavings = savings.reduce((sum, sav) => sum + (sav.amount || 0), 0);
  doc.setFontSize(12);
  doc.setTextColor(147, 51, 234);
  doc.text(`Total Savings: ${formatCurrency(totalSavings)}`, 150, yPos, { align: 'right' });
  
  yPos += 15;
  
  // NET CASHFLOW
  const netCashflow = netSalary - totalExpenses - totalSavings;
  doc.setFontSize(16);
  doc.setTextColor(netCashflow >= 0 ? 34 : 220, netCashflow >= 0 ? 139 : 38, netCashflow >= 0 ? 34 : 38);
  doc.text(`NET CASHFLOW: ${formatCurrency(Math.abs(netCashflow))}`, 105, yPos, { align: 'center' });
  
  if (netCashflow < 0) {
    doc.setFontSize(10);
    doc.setTextColor(220, 38, 38);
    doc.text('⚠ Overspending - Reduce expenses or increase income', 105, yPos + 7, { align: 'center' });
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Nickle - Smart Budgets Meet Big Ambitions', 105, 285, { align: 'center' });
  doc.text('www.nickle.co.za', 105, 290, { align: 'center' });
  
  // Save
  doc.save('Nickle-Cashflow-Statement.pdf');
};

export const exportCarCalculatorToPDF = (netSalary, results, inputs) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(37, 99, 235);
  doc.text('Car Affordability Calculator', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by Nickle', 105, 27, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), 105, 32, { align: 'center' });
  
  let yPos = 50;
  
  // Summary Box
  doc.setFillColor(239, 246, 255);
  doc.rect(20, yPos - 5, 170, 30, 'F');
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('You can afford a car worth', 105, yPos, { align: 'center' });
  
  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235);
  doc.text(formatCurrency(results.affordableCarPrice), 105, yPos + 12, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(34, 139, 34);
  doc.text('✓ Within Budget', 105, yPos + 20, { align: 'center' });
  
  yPos += 40;
  
  // Monthly Costs
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Monthly Costs', 20, yPos);
  
  yPos += 5;
  doc.autoTable({
    startY: yPos,
    head: [['Item', 'Amount']],
    body: [
      ['Monthly Repayment', formatCurrency(results.breakdown.repayment)],
      ['Insurance', formatCurrency(results.breakdown.insurance)],
      ['Petrol', formatCurrency(results.breakdown.petrol)],
      ['Total Monthly Cost', formatCurrency(results.totalMonthlyCost)]
    ],
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235] },
    margin: { left: 20, right: 20 },
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Loan Details
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Loan Details', 20, yPos);
  
  yPos += 5;
  doc.autoTable({
    startY: yPos,
    head: [['Parameter', 'Value']],
    body: [
      ['Monthly Salary', formatCurrency(netSalary)],
      ['Budget for Car', `${inputs.budgetPercentage}%`],
      ['Deposit', formatCurrency(inputs.deposit)],
      ['Loan Term', `${inputs.term} months`],
      ['Interest Rate', `${inputs.interestRate}%`]
    ],
    theme: 'grid',
    headStyles: { fillColor: [100, 100, 100] },
    margin: { left: 20, right: 20 },
  });
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Nickle - Smart Budgets Meet Big Ambitions', 105, 285, { align: 'center' });
  doc.text('www.nickle.co.za', 105, 290, { align: 'center' });
  
  doc.save('Nickle-Car-Calculator.pdf');
};

export const exportHouseCalculatorToPDF = (netSalary, results, inputs) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(34, 139, 34);
  doc.text('Home Affordability Calculator', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by Nickle', 105, 27, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), 105, 32, { align: 'center' });
  
  let yPos = 50;
  
  // Summary Box
  doc.setFillColor(240, 253, 244);
  doc.rect(20, yPos - 5, 170, 30, 'F');
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('You can afford a home worth', 105, yPos, { align: 'center' });
  
  doc.setFontSize(24);
  doc.setTextColor(34, 139, 34);
  doc.text(formatCurrency(results.affordableHousePrice), 105, yPos + 12, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(34, 139, 34);
  doc.text('✓ Within Budget', 105, yPos + 20, { align: 'center' });
  
  yPos += 40;
  
  // Monthly Costs
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Monthly Costs', 20, yPos);
  
  yPos += 5;
  doc.autoTable({
    startY: yPos,
    head: [['Item', 'Amount']],
    body: [
      ['Bond Repayment', formatCurrency(results.breakdown.bondRepayment)],
      ['Rates & Taxes', formatCurrency(results.breakdown.rates)],
      ['Home Insurance', formatCurrency(results.breakdown.insurance)],
      ['Maintenance', formatCurrency(results.breakdown.maintenance)],
      ['Total Monthly Cost', formatCurrency(results.totalMonthlyCost)]
    ],
    theme: 'grid',
    headStyles: { fillColor: [34, 139, 34] },
    margin: { left: 20, right: 20 },
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Upfront Costs
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Upfront Costs', 20, yPos);
  
  yPos += 5;
  doc.autoTable({
    startY: yPos,
    head: [['Item', 'Amount']],
    body: [
      ['Down Payment', formatCurrency(results.downPayment)],
      ['Transfer Duty', formatCurrency(results.transferDuty)],
      ['Bond Registration', formatCurrency(results.bondRegistration)],
      ['Bond Initiation', formatCurrency(results.bondInitiation)],
      ['Total Upfront', formatCurrency(results.totalUpfront)]
    ],
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235] },
    margin: { left: 20, right: 20 },
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Loan Details
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Loan Details', 20, yPos);
  
  yPos += 5;
  doc.autoTable({
    startY: yPos,
    head: [['Parameter', 'Value']],
    body: [
      ['Monthly Salary', formatCurrency(netSalary)],
      ['Budget for Housing', `${inputs.budgetPercentage}%`],
      ['Down Payment', `${inputs.downPaymentPercentage}%`],
      ['Loan Term', `${inputs.term / 12} years`],
      ['Interest Rate', `${inputs.interestRate}%`]
    ],
    theme: 'grid',
    headStyles: { fillColor: [100, 100, 100] },
    margin: { left: 20, right: 20 },
  });
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Nickle - Smart Budgets Meet Big Ambitions', 105, 285, { align: 'center' });
  doc.text('www.nickle.co.za', 105, 290, { align: 'center' });
  
  doc.save('Nickle-House-Calculator.pdf');
};

